

-- Steps to build the WAFPATTERNS database (with ij derby TOOL).

connect 'jdbc:derby:/home/reiern/opt/derby/WAFPATTERNS;create=true';

CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY('derby.user.wafpatterns', '');
    
CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY('derby.database.fullAccessUsers', 'wafpatterns');

CREATE SCHEMA WAFPATTERNS;

CREATE TABLE WAFPATTERNS.SH_CHARTVIEWS (
	USERID VARCHAR(100) NOT NULL,
	FORM VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	ISDEFAULT CHAR(1) DEFAULT NULL,
	CHARTSETTINGS BLOB(15728640) DEFAULT NULL);
	
CREATE TABLE WAFPATTERNS.SH_REPORTS (
	USERID VARCHAR(100) NOT NULL,
	FORM VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	TYPE INTEGER NOT NULL,
	ISDEFAULT CHAR(1) DEFAULT NULL,
	REPORTSETTINGS BLOB(15728640) DEFAULT NULL, 
	CONSTRAINT WAFPATTERNS.REPORTS_PK PRIMARY KEY(USERID, FORM, NAME));
	

CREATE TABLE WAFPATTERNS.SHB_DASHBOARDS (
	DASHBOARDID VARCHAR(100) NOT NULL,
	DASHBOARD_USER VARCHAR(100) NOT NULL,
	DASH_PROPERTIES CLOB(64K)  DEFAULT NULL,	 
	CONSTRAINT WAFPATTERNS.DASHBOARDS_PK PRIMARY KEY(DASHBOARDID, DASHBOARD_USER));
	
CREATE TABLE WAFPATTERNS.SHB_DASHBOARD_DETAILS (
	DASHBOARDID VARCHAR(100) NOT NULL,
	TEMPLATE_FORM VARCHAR(100) NOT NULL,
	TEMPLATE_NAME VARCHAR(100) NOT NULL,
	TEMPLATE_USER VARCHAR(100) NOT NULL,
	PROPERTIES CLOB(64K)  DEFAULT NULL,
	CONSTRAINT WAFPATTERNS.DASHBOARDS_DE_PK PRIMARY KEY(DASHBOARDID, TEMPLATE_FORM, TEMPLATE_NAME, TEMPLATE_USER));
	
CREATE TABLE WAFPATTERNS.SH_REPORTTEMPLATES (
	USERID VARCHAR(100) NOT NULL,
	PAGE VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	ISDEFAULT CHAR(1) DEFAULT NULL,
	REPORTSETTINGS BLOB(15728640) DEFAULT NULL, 
	CONSTRAINT WAFPATTERNS.REPORTTEMPLATES_PK PRIMARY KEY(USERID, PAGE, NAME));	
		
CREATE TABLE WAFPATTERNS.FORMTEMPLATES (
	USERID VARCHAR(100) NOT NULL,
	FORM VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL, 
	"DESCRIPTOR" BLOB(15728640) DEFAULT NULL,
	RECORD BLOB(15728640) DEFAULT NULL,
	ISDEFAULT CHAR(1) DEFAULT NULL,
	"MODE" INTEGER NOT NULL,
	ISPUBLIC CHAR(1) DEFAULT NULL, 
	CONSTRAINT WAFPATTERNS.FORMTEMPLATES_PK PRIMARY KEY( USERID , FORM , NAME , "MODE" ) );
	
CREATE TABLE WAFPATTERNS.SH_MESSAGES
  (MESSAGE_ID INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
   USERID VARCHAR(100) NOT NULL,
   SENDERID VARCHAR(100) NOT NULL,
   SUBJECT VARCHAR(200),
   MESSAGE CLOB(64K)  DEFAULT NULL,
   CREATIONDATE TIMESTAMP NOT NULL,
   EXPIRYDATE TIMESTAMP NOT NULL, 
   STATUS INTEGER NOT NULL);
   
ALTER TABLE WAFPATTERNS.SH_MESSAGES ADD CONSTRAINT SH_MESSAGES_PK PRIMARY KEY (MESSAGE_ID);

CREATE TABLE WAFPATTERNS.COUNTRIES
  (COUNTRY_ID INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
   NAME CHARACTER(30) NOT NULL,
   NATIONALITY CHARACTER(30) NOT NULL,
   SHORTDESC CHARACTER(100));

ALTER TABLE WAFPATTERNS.COUNTRIES
  ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (COUNTRY_ID);

ALTER TABLE WAFPATTERNS.COUNTRIES
  ADD CONSTRAINT COUNTRY_NAME_UNIQ UNIQUE (NAME);

CREATE TABLE WAFPATTERNS.DOCTORS
  (DOCTOR_ID INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
   LASTNAME CHARACTER(30) NOT NULL,
   FIRSTNAME CHARACTER(30) NOT NULL,
   REGISTERED DATE,
   BORN DATE,
   PHONE INTEGER NOT NULL,
   EMAIL CHARACTER(30) NOT NULL,
   ADDRESS CHARACTER(200) NOT NULL,
   COUNTRY_ID INTEGER NOT NULL);   
      
ALTER TABLE WAFPATTERNS.DOCTORS
  ADD CONSTRAINT DOCTORS_PK PRIMARY KEY (DOCTOR_ID);


ALTER TABLE WAFPATTERNS.DOCTORS
  ADD CONSTRAINT DOCTORS_FKCOUNTRY FOREIGN KEY (COUNTRY_ID)
  REFERENCES WAFPATTERNS.COUNTRIES(COUNTRY_ID)
  ON DELETE RESTRICT;
  
ALTER TABLE WAFPATTERNS.DOCTORS
  ADD CONSTRAINT DOCTORS_NAME_UNIQ UNIQUE (LASTNAME, FIRSTNAME);
	
CREATE TABLE WAFPATTERNS.PATIENTS
   (PATIENT_ID INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
   LASTNAME CHARACTER(40) NOT NULL,
   FIRSTNAME CHARACTER(40) NOT NULL,
   GENDER CHARACTER(1) NOT NULL,
   REGISTERED DATE,
   BORN DATE,
   HEIGHT DOUBLE NOT NULL,
   WEIGHT DOUBLE NOT NULL,   
   PHONE INTEGER NOT NULL,
   EMAIL CHARACTER(40) NOT NULL,
   ADDRESS CHARACTER(200) NOT NULL,
   COUNTRY_ID INTEGER NOT NULL,
   LANGUAGE INTEGER NOT NULL);

ALTER TABLE WAFPATTERNS.PATIENTS
  ADD CONSTRAINT PATIENTS_PK PRIMARY KEY (PATIENT_ID);
  
ALTER TABLE WAFPATTERNS.PATIENTS
  ADD CONSTRAINT PATIENTS_FK FOREIGN KEY (COUNTRY_ID)
  REFERENCES WAFPATTERNS.COUNTRIES(COUNTRY_ID)
  ON DELETE RESTRICT;
     
CREATE TABLE WAFPATTERNS.SPECIALIZATIONS
  (SPECIALIZATION_ID INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
   NAME VARCHAR(200) NOT NULL,
   DESCRIPTION VARCHAR(500), 
   ACRONYM VARCHAR(3) NOT NULL);
  
ALTER TABLE WAFPATTERNS.SPECIALIZATIONS
  ADD CONSTRAINT SPECIALIZA_PK PRIMARY KEY (SPECIALIZATION_ID);
  
ALTER TABLE WAFPATTERNS.SPECIALIZATIONS
  ADD CONSTRAINT SPE_NAME_UNIQ UNIQUE (NAME);


CREATE TABLE WAFPATTERNS.DOCTORS_PATIENTS
  (DOCTOR_ID INTEGER NOT NULL,   
   PATIENT_ID INTEGER NOT NULL);
   
ALTER TABLE WAFPATTERNS.DOCTORS_PATIENTS
  ADD CONSTRAINT DOC_PAT_PK PRIMARY KEY (DOCTOR_ID, PATIENT_ID);
    
ALTER TABLE WAFPATTERNS.DOCTORS_PATIENTS
  ADD CONSTRAINT DOC_DOC_ID_FK FOREIGN KEY (DOCTOR_ID)
  REFERENCES WAFPATTERNS.DOCTORS(DOCTOR_ID)
  ON DELETE RESTRICT;
  
ALTER TABLE WAFPATTERNS.DOCTORS_PATIENTS
  ADD CONSTRAINT DOC_PAT_CUST_ID_FK FOREIGN KEY (PATIENT_ID)
  REFERENCES WAFPATTERNS.PATIENTS(PATIENT_ID)
  ON DELETE RESTRICT;


CREATE TABLE WAFPATTERNS.DOCTORS_LANGUAGES
  (DOCTOR_ID INTEGER NOT NULL,   
   LANGUAGE INTEGER NOT NULL,
   LEVEL INTEGER NOT NULL);
   
ALTER TABLE WAFPATTERNS.DOCTORS_LANGUAGES
  ADD CONSTRAINT DOC_LAN_PK PRIMARY KEY (DOCTOR_ID, LANGUAGE);
    
ALTER TABLE WAFPATTERNS.DOCTORS_LANGUAGES
  ADD CONSTRAINT DOC_LAN_ID_FK FOREIGN KEY (DOCTOR_ID)
  REFERENCES WAFPATTERNS.DOCTORS(DOCTOR_ID)
  ON DELETE RESTRICT;
      

CREATE TABLE WAFPATTERNS.DOCTORS_SPECIALIZATIONS
  (DOCTOR_ID INTEGER NOT NULL,   
   SPECIALIZATION_ID INTEGER NOT NULL);
   
ALTER TABLE WAFPATTERNS.DOCTORS_SPECIALIZATIONS
  ADD CONSTRAINT DOC_SPE_PK PRIMARY KEY (DOCTOR_ID, SPECIALIZATION_ID);
    
ALTER TABLE WAFPATTERNS.DOCTORS_SPECIALIZATIONS
  ADD CONSTRAINT DOC_SPE_DOC_ID_FK FOREIGN KEY (DOCTOR_ID)
  REFERENCES WAFPATTERNS.DOCTORS(DOCTOR_ID)
  ON DELETE RESTRICT;
  
ALTER TABLE WAFPATTERNS.DOCTORS_SPECIALIZATIONS
  ADD CONSTRAINT DOC_SPE_SPE_ID_FK FOREIGN KEY (SPECIALIZATION_ID)
  REFERENCES WAFPATTERNS.SPECIALIZATIONS(SPECIALIZATION_ID)
  ON DELETE RESTRICT;


INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Allergology and Immunology', '', 'ALI');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Anaesthesia and intensive therapy', '', 'AIT');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Balneology and medical recuperation', '', 'BMR');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Cardiology', '', 'CAR');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Cardiovascular surgery', '', 'CSU');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Dermatovenerology', '', 'DER');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Endocrinology', '', 'END');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Gastroenterology', '', 'GAS');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('General Oncology and Chemotherapy', '', 'GOC');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('General surgery', '', 'GSU');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Haematology', '', 'HAE');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Infantile neurology', '', 'INE');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Infantile psychiatry', '', 'IPS');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Infantile surgery', '', 'ISU');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Infectious Diseases', '', 'IND');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Internal medicine', '', 'IME');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Neonatology', '', 'NEO');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Nephrology', '', 'NEP');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Neurology', '', 'NEG');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Neurosurgery', '', 'NEU');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Nutrition and metabolic diseases', '', 'NME');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Obstetric and gynaecology', '', 'OaG');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Ophthalmology', '', 'OPH');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Orthopedics', '', 'ORT');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Pathological Anatomy', '', 'PAN');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Pediatrics', '', 'PED');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Physiology', '', 'PHY');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Plastic surgery', '', 'PSU');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Pneumophysiology', '', 'PNE');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Rheumatology', '', 'REH');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Psychiatry', '', 'PSY');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Stomatology', '', 'STO'); 
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Thoracic surgery', '', 'TSU');
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Traumatology', '', 'TRA'); 
INSERT INTO WAFPATTERNS.SPECIALIZATIONS(NAME, DESCRIPTION, ACRONYM) values('Urology', '', 'URO');





DROP TABLE WAFPATTERNS.DOCTORS;
DROP TABLE WAFPATTERNS.SH_MESSAGES;
DROP TABLE WAFPATTERNS.COUNTRIES;
DROP TABLE WAFPATTERNS.PATIENTS;
DROP TABLE WAFPATTERNS.SPECIALIZATIONS;
DROP TABLE WAFPATTERNS.REPORTTEMPLATES;
