package com.antilia.letsplay.domain;

// Generated Apr 23, 2008 5:11:37 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Tuplizer;

import com.antilia.hibernate.remote.TuplizerImpl;
import com.antilia.web.crud.Exclude;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "user", uniqueConstraints = @UniqueConstraint(columnNames = "logname"))
@Tuplizer(impl=TuplizerImpl.class)
public class User implements java.io.Serializable, Comparable<User> {

	private static final long serialVersionUID = 1L;
	
	@Exclude
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name="country_seq",sequenceName="country_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	@Column(name = "name", unique = false, nullable = false, length = 40)
	private String name;
	
	@Column(name = "lastname", unique = false, nullable = false, length = 40)
	private String lastName;
	
	@Column(name = "logname", unique = true, nullable = false, length = 40)
	private String logname;
	
	@Column(name = "password", unique = false, nullable = false, length = 40)
	private String password;
	
	@Column(name = "email", unique = false, nullable = false, length = 60)
	private String email;
	
	@Enumerated(EnumType.STRING)
	@Column(name = "role", unique = false, nullable = false, length = 20)
	private Role role;
	
	@ManyToOne
	@JoinColumn(name="parent", nullable = true)
	private User parent;
	
	public User() {
	}

	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	
	@Override
	public String toString() {
		return getName() + " " + getLastName();
	}
	
	@Override
	public boolean equals(Object obj) {
		if(obj instanceof User) {
			return (logname.equals(((User)obj).getLogname()));
		}
		return false;
	}


	@Override
	public int compareTo(User o) {
		return getLogname().compareTo(o.getLogname());
	}
	
	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public String getLastName() {
		return lastName;
	}


	public void setLastName(String lastName) {
		this.lastName = lastName;
	}


	public Role getRole() {
		return role;
	}


	public void setRole(Role role) {
		this.role = role;
	}


	public User getParent() {
		return parent;
	}


	public void setParent(User parent) {
		this.parent = parent;
	}


	public String getLogname() {
		return logname;
	}


	public void setLogname(String logname) {
		this.logname = logname;
	}


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}
}
