package com.antilia.demo.manager.entities;

// Generated Apr 23, 2008 5:11:37 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.antilia.web.crud.Exclude;
import com.antilia.web.field.impl.SelectionMode;
import com.antilia.web.field.impl.SelectionType;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address")
public class Address implements java.io.Serializable, Comparable<Address> {

	private static final long serialVersionUID = 1L;
	
	@Exclude
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name="address_seq",sequenceName="address_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "city", nullable = false)
	@SelectionType(type=SelectionMode.LARGE_ON_NEXT_PAGE)
	private City city;
	
	@Column(name = "address1", nullable = false, length = 300)	
	private String address1;
	
	@Column(name = "address2", length = 300)
	private String address2;
	
	@Column(name = "address3", length = 300)
	private String address3;
	
	@Column(name = "zipcode", length = 40)
	private String zipcode;
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "address")
	private Set<Customer> customers = new HashSet<Customer>(0);
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "address")
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Address() {
	}

	public Address(Long id, City city, String address1) {
		this.id = id;
		this.city = city;
		this.address1 = address1;
	}

	public Address(Long id, City city, String address1, String address2,
			String address3, String zipcode, Set<Customer> customers,
			Set<Employee> employees) {
		this.id = id;
		this.city = city;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.zipcode = zipcode;
		this.customers = customers;
		this.employees = employees;
	}

	@Override
	public String toString() {
		return address1 + "," + this.city;
	}
	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}
	
	public int compareTo(Address o) {
		return address1.compareTo(o.getAddress1());
	}

}
