package com.antilia.demo.manager.entities;

// Generated Apr 23, 2008 5:11:37 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chargerate generated by hbm2java
 */
@Entity
@Table(name = "chargerate")
public class Chargerate implements java.io.Serializable {

	private long id;
	private Customer customer;
	private long role;
	private BigDecimal chargeperhour;

	public Chargerate() {
	}

	public Chargerate(long id, Customer customer, long role) {
		this.id = id;
		this.customer = customer;
		this.role = role;
	}

	public Chargerate(long id, Customer customer, long role,
			BigDecimal chargeperhour) {
		this.id = id;
		this.customer = customer;
		this.role = role;
		this.chargeperhour = chargeperhour;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "role", nullable = false)
	public long getRole() {
		return this.role;
	}

	public void setRole(long role) {
		this.role = role;
	}

	@Column(name = "chargeperhour", precision = 3)
	public BigDecimal getChargeperhour() {
		return this.chargeperhour;
	}

	public void setChargeperhour(BigDecimal chargeperhour) {
		this.chargeperhour = chargeperhour;
	}

}
