package com.antilia.letsplay.domain;

// Generated Apr 23, 2008 5:11:37 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Tuplizer;

import com.antilia.hibernate.remote.TuplizerImpl;
import com.antilia.web.crud.Exclude;
import com.antilia.web.field.impl.DrillInSelectionMode;
import com.antilia.web.field.impl.SelectionType;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "word", uniqueConstraints = @UniqueConstraint(columnNames = "text"))
@Tuplizer(impl=TuplizerImpl.class)
public class DWord implements java.io.Serializable, Comparable<DWord>, ITranslatable {

	private static final long serialVersionUID = 1L;
	
	@Exclude
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name="country_seq",sequenceName="country_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	@Column(name = "text", unique = true, nullable = false, length = 40)
	private String text;

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image", nullable = true)
	@SelectionType(type=DrillInSelectionMode.LARGE_ON_NEXT_PAGE)
	private DImage image;
	
	public DWord() {
	}

	public DWord(long id, String text) {
		this.id = id;
		setText(text);
	}

	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	

	public int compareTo(DWord o) {
		return getText().compareTo(o.getText());
	}
	
	@Override
	public String toString() {
		return getText();
	}
	
	public String getText() {
		return text;
	}

	public void setText(String text) {
		if(text != null)			
			this.text = text.trim().toUpperCase();
	}

	public DImage getImage() {
		return image;
	}

	public void setImage(DImage image) {
		this.image = image;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((text == null) ? 0 : text.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DWord other = (DWord) obj;
		if (text == null) {
			if (other.text != null)
				return false;
		} else if (!text.equals(other.text))
			return false;
		return true;
	}
	
	@Override
	public String getTranslationKey() {
		return this.text.toLowerCase();
	}
}
