package com.antilia.letsplay.domain;

// Generated Apr 23, 2008 5:11:37 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Tuplizer;

import com.antilia.hibernate.remote.TuplizerImpl;
import com.antilia.letsplay.Language;
import com.antilia.web.crud.Exclude;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "translation", uniqueConstraints = @UniqueConstraint(columnNames = {"text", "original","target"}))
@Tuplizer(impl=TuplizerImpl.class)
public class Translation implements java.io.Serializable,  ITranslatable {

	private static final long serialVersionUID = 1L;
	
	@Exclude
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name="country_seq",sequenceName="country_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	@Column(name = "text", unique = false, nullable = false, length = 40)
	private String text;

	@Column(name = "translation", unique = false, nullable = false, length = 40)
	private String translation;
	
	@Enumerated(EnumType.STRING)
	@Column(name = "original", unique = false, nullable = false, length = 40)
	private Language original;
	
	@Enumerated(EnumType.STRING)
	@Column(name = "target", unique = false, nullable = false, length = 40)
	private Language target;
	
	public Translation() {
	}

	public Translation(long id, String text) {
		this.id = id;
		setText(text);
	}

	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@Override
	public String toString() {
		return getText();
	}
	
	public String getText() {
		return text;
	}

	public void setText(String text) {
		if(text != null)			
			this.text = text.trim().toUpperCase();
	}

	
	@Override
	public String getTranslationKey() {
		return this.text.toLowerCase();
	}

	public String getTranslation() {
		return translation;
	}

	public void setTranslation(String translation) {
		this.translation = translation;
	}

	public Language getOriginal() {
		return original;
	}

	public void setOriginal(Language original) {
		this.original = original;
	}

	public Language getTarget() {
		return target;
	}

	public void setTarget(Language target) {
		this.target = target;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((original == null) ? 0 : original.hashCode());
		result = prime * result + ((target == null) ? 0 : target.hashCode());
		result = prime * result + ((text == null) ? 0 : text.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Translation other = (Translation) obj;
		if (original == null) {
			if (other.original != null)
				return false;
		} else if (!original.equals(other.original))
			return false;
		if (target == null) {
			if (other.target != null)
				return false;
		} else if (!target.equals(other.target))
			return false;
		if (text == null) {
			if (other.text != null)
				return false;
		} else if (!text.equals(other.text))
			return false;
		return true;
	}
}
